### ISSUE TITLE
ArchLinux JDK - SIGSEGV

### ISSUE THREAD

**Issue by TheAifam5** [JetBrains/jdk8u#11]
Hey,
we, ArchLinux users, have problems with this JDK.
Actually JDK can be fully compiled but can not be run.

Logs: https://pastebin.com/qJCr2JcU

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb3098daeeb, pid=2041, tid=0x00007fb2f05b0700
#
# JRE version: OpenJDK Runtime Environment (8.0_152-b39) (build 1.8.0_152-b1063)
# Java VM: OpenJDK 64-Bit Server VM (25.152-b1063 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x7cdeeb]
#
# Core dump written. Default location: /home/xxxx/Downloads/java8-openjdk-jetbrains/core or core.2041
#
# An error report file with more information is saved as:
# /home/xxxx/Downloads/java8-openjdk-jetbrains/hs_err_pid2041.log
[thread 140406511298304 also had an error]
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (build 1.8.0_152-b1063)
OpenJDK 64-Bit Server VM (build 25.152-b1063, mixed mode)

[error occurred during error reporting , id 0xb]

#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[1]    2041 abort (core dumped)  java -version
```

GDB Registers:
```
(gdb) info registers
rax            0x6	6
rbx            0x2100800	34605056
rcx            0xcafebabe	3405691582
rdx            0x0	0
rsi            0x0	0
rdi            0x7ffff71d6a20	140737339288096
rbp            0x7ffff71d6a20	0x7ffff71d6a20
rsp            0x7ffff7fd47b8	0x7ffff7fd47b8
r8             0x7ffff7fd4600	140737353958912
r9             0xc	12
r10            0x2	2
r11            0x7fffe1000374	140736968262516
r12            0x7ffff7fd4a10	140737353959952
r13            0x7ffff71a7130	140737339093296
r14            0x7ffff000b590	140737219966352
r15            0x7ffff000b5e0	140737219966432
rip            0x7fffe10002b4	0x7fffe10002b4
eflags         0x210246	[ PF ZF IF RF ID ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0

(gdb) bt
#0  0x00007fffe10002b4 in ?? ()
#1  0x0000000000000246 in ?? ()
#2  0x00007fffe1000160 in ?? ()
#3  0x00007ffff71d69dc in ?? () from /usr/lib/jvm/java-8-openjdk-jetbrains/jre/lib/amd64/server/libjvm.so
#4  0x00007ffff7fd49e0 in ?? ()
#5  0x00007ffff6d00134 in ?? () from /usr/lib/jvm/java-8-openjdk-jetbrains/jre/lib/amd64/server/libjvm.so
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

Regards,
TheAifam5

**Comment by avu** [comment]
Hello, we've made a huge number of updates. Do you still have this problem?

**Comment by TheAifam5** [comment]
@avu for now, everything works fine. :D I think this issue can be closed now.

PS. I forgot about this issue :D
